<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>CarRace.Harness</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CarRace.Vehicle/CarRace.Vehicle.csproj" />
    <ProjectReference Include="../CarRace.Track/CarRace.Track.csproj" />
  </ItemGroup>
</Project>
